import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  platform: 'node',
  // Resolve packages that publish a dedicated "browser" export condition
  // (currently: cheerio) to that build instead of their Node-oriented one.
  // cheerio's default entry pulls in fromURL()'s encoding-sniffer ->
  // iconv-lite chain, which does `require('buffer')`/`require('stream')`/
  // `require('string_decoder')` and reads bare `process.*` globals at
  // module-load time. That is fine on desktop, where Electron has Node, but
  // none of it exists on Obsidian mobile, so evaluating the bundle crashed
  // the whole plugin on iPadOS before it rendered anything (a "VB.Buffer"
  // TypeError). cheerio ships a browser build specifically to avoid this
  // (dist/browser/*, no encoding-sniffer at all, since only fromURL() needs
  // it and this plugin only ever calls cheerio.load() on an already-fetched
  // HTML string), so this setting is a zero-dependency fix rather than
  // adding Buffer/process/stream polyfills. No other dependency here defines
  // a "browser" condition, so this does not change resolution for anything
  // else.
  //
  // Keep this in place when the importer moves in. It is the kind of setting
  // that looks removable until someone opens the plugin on a phone.
  conditions: ['browser'],
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outdir: './',
  minify: prod,
  loader: {
    '.css': 'css',
    // The settings page's "what's new" panel shows the package's own
    // CHANGELOG.md, imported as a string so the notes in Obsidian and the
    // released notes cannot drift apart. See src/types/markdown.d.ts.
    '.md': 'text',
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
