/**
 * The credit line under APERtrail's printed sheets.
 *
 * Every sheet in the suite now ends the same way as NODAtrail's: which sheet,
 * who made it when the `exportAuthor` setting names somebody, the date, the
 * plugin, and technosoftware.com as a link whose text is its address.
 */
import { describe, expect, it } from 'vitest';
import { SHEET_CONTRACT } from '@technosoftware/trail-core';
import { sheetCredit } from '../src/shared/sheet-credit';
import { DEFAULT_SETTINGS } from '../src/settings/defaults';
import { buildCostSheetHtml, CostSheet } from '../src/trips/costs/export-trip-costs';

const named = (author: string) => `Cost sheet generated by ${author} on 15 Sep 2026 with APERtrail`;
const anonymous = () => 'Cost sheet generated on 15 Sep 2026 with APERtrail';

describe('the words', () => {
  it('names the author when one is set', () => {
    expect(sheetCredit({ exportAuthor: 'Thomas' }, named, anonymous)).toBe(
      'Cost sheet generated by Thomas on 15 Sep 2026 with APERtrail'
    );
  });

  it('leaves the name out when the setting is blank or only spaces', () => {
    expect(sheetCredit({ exportAuthor: '' }, named, anonymous)).toBe(anonymous());
    expect(sheetCredit({ exportAuthor: '   ' }, named, anonymous)).toBe(anonymous());
  });
});

describe('the defaults', () => {
  it('come from the contract NODAtrail shares', () => {
    expect(DEFAULT_SETTINGS.exportAuthor).toBe(SHEET_CONTRACT.exportAuthor);
    expect(DEFAULT_SETTINGS.exportsSubfolder).toBe(SHEET_CONTRACT.exportsSubfolder);
  });
});

describe('on the page', () => {
  it('prints the record, then the credit with its link, and escapes the name', () => {
    const sheet = {
      title: 'Costs',
      subtitle: null,
      dateRange: null,
      currencyLines: [],
      summary: [],
      rows: [],
      totals: [],
      optional: null,
      balances: [],
      transfers: [],
      labels: {
        bookings: '',
        planned: '',
        actual: '',
        total: '',
        settlement: '',
        owes: '',
        rate: '',
        reference: '',
      },
      caveat: 'Caveat.',
      record: 'The notes are the record.',
      footer: named('<b>Tom</b>'),
    } as unknown as CostSheet;

    const html = buildCostSheetHtml(sheet);
    expect(html).toContain('<p>The notes are the record.</p>');
    expect(html).toContain('generated by &lt;b&gt;Tom&lt;/b&gt; on');
    expect(html).toContain(' - <a href="https://technosoftware.com">technosoftware.com</a></p>');
    expect(html.indexOf('The notes are the record.')).toBeLessThan(html.indexOf('technosoftware'));
  });
});
